version: '2'
services:
  web:
    image: nginx:latest
    restart: always
    working_dir: /app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./:/app
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php

#  php:
#    image: dmstr/php-yii2:latest
#    restart: always
#    working_dir: /app
#    environment:
#      - PHP_ENABLE_XDEBUG
#      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#    volumes:
#      - ./:/app
#      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
#      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
#    links:
#      - mysql
#  mysql:
#    image: mysql:5
#    restart: always
#    environment:
#      - MYSQL_DATABASE
#      - MYSQL_ROOT_PASSWORD
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#    ports:
#      - ${MYSQL_PORT}:3306
#    volumes:
#      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
